name = "Ecophys"
uuid = "19467474-d12d-47c9-939f-3e50fbfd93ad"
authors = ["Alejandro Morales <alejandro.moralessierra@wur.nl> and contributors"]
version = "0.1.0"

[deps]
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Roots = "2.0.19"
SpecialFunctions = "2.3.1"
Unitful = "1.17.0"
julia = "1"
